# updated 2021
# dev theme = Development - 2021
# https://bagbalm.com/?preview_theme_id=121190613173
development:
  password: e67ba686787a14534897578865d0e004
  theme_id: "121190613173"
  store: vermonts-original-bag-balm.myshopify.com
  ignore_files:
  - config/settings_data.json

# ALERT!! - FOR SOME REASON I COULD NOT DEPLOY ON PRODUCTION - ONLY USING WATCH 
# production:
#   password: e67ba686787a14534897578865d0e004
#   theme_id: "44655444027"
#   store: vermonts-original-bag-balm.myshopify.com
#   ignore_files:
#   - config/settings_data.json